<?php
$config = [
	'meta' => '<meta{{attrs}}/>',
	'metalink' => '<link href="{{url}}"{{attrs}}/>',
	'link' => '<a href="{{url}}"{{attrs}}>{{content}}</a>',
	'mailto' => '<a href="mailto:{{url}}"{{attrs}}>{{content}}</a>',
	'image' => '<img src="{{url}}"{{attrs}}/>',
	'tableheader' => '<th{{attrs}}>{{content}}</th>',
	'tableheaderrow' => '<tr{{attrs}}>{{content}}</tr>',
	'tablecell' => '<td{{attrs}}>{{content}}</td>',
	'tablerow' => '<tr{{attrs}}>{{content}}</tr>',
	'block' => '<div{{attrs}}>{{content}}</div>',
	'blockstart' => '<div{{attrs}}>',
	'blockend' => '</div>',
	'tag' => '<{{tag}}{{attrs}}>{{content}}</{{tag}}>',
	'tagstart' => '<{{tag}}{{attrs}}>',
	'tagend' => '</{{tag}}>',
	'tagselfclosing' => '<{{tag}}{{attrs}}/>',
	'para' => '<p{{attrs}}>{{content}}</p>',
	'parastart' => '<p{{attrs}}>',
	'css' => '<link rel="{{rel}}" href="{{url}}"{{attrs}}/>',
	'style' => '<style{{attrs}}>{{content}}</style>',
	'charset' => '<meta http-equiv="Content-Type" content="text/html; charset={{charset}}" />',
	'ul' => '<ul{{attrs}}>{{content}}</ul>',
	'ol' => '<ol{{attrs}}>{{content}}</ol>',
	'li' => '<li{{attrs}}>{{content}}</li>',
	'javascriptblock' => '<script{{attrs}}>{{content}}</script>',
	'javascriptstart' => '<script>',
	'javascriptlink' => '<script src="{{url}}"{{attrs}}></script>',
	'javascriptend' => '</script>'
];
